---
name: "stale-repos"
author: "github"
description: "A GitHub Action to identify stale repos within an organization"
outputs:
  inactiveRepos:
    description: "Inactive Repos in the organization"
runs:
  using: "docker"
  image: "docker://ghcr.io/github-community-projects/stale_repos:v7"
branding:
  icon: "check-square"
  color: "white"
